export const shopItems = [
  {
    id: '1',
    itemId: 'ruong_linh_bao',
    name: 'Rương Linh Bảo',
    cost: 10,
    currency: 'Tinh thạch',
    itemType: 'tinh_thach',
    image: '/ruong-linh-bao.webp',
  },
  {
    id: '2',
    itemId: 'ruong_linh_bao',
    name: 'Rương Linh Bảo',
    cost: 30,
    currency: 'Tinh huyết',
    itemType: 'tinh_huyet',
    image: '/ruong-linh-bao.webp',
  },
  {
    id: '3',
    itemId: 'ruong_linh_bao',
    name: 'Rương Linh Bảo',
    cost: 20,
    currency: 'Mảnh Rương Linh Bảo',
    itemType: 'manh_ruong_linh_bao',
    image: '/ruong-linh-bao.webp',
  },
  {
    id: '4',
    itemId: 'ruong_phap_bao',
    name: 'Rương Pháp Bảo (1)',
    cost: 50,
    currency: 'Mảnh Rương Pháp Bảo',
    itemType: 'manh_ruong_phap_bao',
    image: '/ruong-phap-bao.webp',
  },
  {
    id: '5',
    itemId: 'ruong_phap_bao',
    name: 'Rương Pháp Bảo (2)',
    cost: 50,
    currency: 'Mảnh Rương Pháp Bảo',
    itemType: 'manh_ruong_phap_bao',
    image: '/ruong-phap-bao.webp',
  },
  {
    id: '6',
    itemId: 'ruong_than_phu',
    name: 'Rương Thần Phù',
    cost: 30,
    currency: 'Mảnh Rương Thần Phù',
    itemType: 'manh_ruong_than_phu',
    image: '/ruong-than-phu.webp',
  },
  {
    id: '7',
    itemId: 'ruong_than_phu',
    name: 'Rương Thần Phù',
    cost: 50,
    currency: 'Tinh Huyết',
    itemType: 'tinh_huyet',
    image: '/ruong-than-phu.webp',
  },
  {
    id: '8',
    itemId: 'chia_linh_bao',
    name: 'Chìa Linh Bảo',
    cost: 20,
    currency: 'Tinh Huyết',
    itemType: 'tinh_huyet',
    image: '/chia-linh-bao.png',
  },
];